name: ReaPack Indexer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  index:
    name: Generate index.xml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run reapack-index
        uses: cfillion/reapack-index-action@v1
        with:
          version: '1'
          name: "Floop's Reaper Scripts"
          commit: true
