name: ReaPack Indexer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  index:
    name: Generate index.xml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessario per scansionare la cronologia git

      - name: Run reapack-index
        uses: cfillion/reapack-index-action@v1
        with:
          commit: true
